name: ci

on:
  push:
   branches: 
    - 'main'
   tags:
    - 'v*' 

jobs:
  login:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/165080585157/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
          service_account: 'gha-1000@cloud-resume-2021-335819.iam.gserviceaccount.com'
      
      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: us-central1-docker.pkg.dev/cloud-resume-2021-335819/cloud-resume/static-light
          tags: type=raw,value={{branch}}-{{date 'YYYYMMDD'}}


      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}